name: Merge Dependabot pull requester
on:
  workflow_dispatch:
  schedule:
    - cron: "0,10,20,30,40,50 7-9 * * 1,2,3,4,5"

jobs:
  merge-dependabot-pr:
    uses: navikt/aap-workflows/.github/workflows/merge-dependabot-pr.yml@main
    with:
      disable-dependabot-merge: true
      workflow-id: "build_and_deploy.yaml"
    permissions:
      actions: write
      checks: read
      contents: write
      pull-requests: write
      statuses: read
