name: "Build and deploy aap-innsyn to labs"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}-labs"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"
      - name: "Cache client node_modules"
        id: "cache-node-modules"
        uses: "actions/cache@v3"
        with:
          path: "node_modules"
          key: "${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}"
      - name: "install dependencies Yarn"
        if: "steps.cache-node-modules.outputs.cache-hit != 'true'"
        run: "yarn install --frozen-lockfile"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Copy env-file for labs
        run: cp .nais/labs.env .env.local
      - name: "client tests"
        run: "yarn test"
      - name: "Bygg klient(yarn run build)"
        run: "yarn run build"
      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@v2"
      - name: "Login to GitHub Docker Registry"
        uses: "docker/login-action@v2"
        with:
          "registry": "ghcr.io"
          "username": "${{ github.actor }}"
          "password": "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build and push Docker"
        uses: "docker/build-push-action@v4"
        with:
          context: .
          file: Dockerfile
          tags: "${{ env.IMAGE }}"
          push: "true"
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"
  "deployAppToLabs":
    name: "Deploy app to labs"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy to LABS"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "dev-gcp"
          "RESOURCE": ".nais/nais-mock.yaml"
          "VARS": ".nais/labs.yaml"
