name: Build and deploy aap-innsyn to prod
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
env:
  'IMAGE': ghcr.io/${{ github.repository }}:${{ github.sha }}-prod
jobs:
  'build':
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: 'write'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
          cache: yarn

      - name: Cache node_modules
        id: cache-node-modules

        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

      - name: install dependencies Yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Copy env-file for prod
        run: cp .nais/prod.env .env.local

      - name: Print env
        run: cat .env.local

      - name: client tests
        run: yarn test

      - name: check diff on translations
        run: yarn intl:diff

      - name: Bygg klient(yarn run build)
        run: yarn run build

      - name: Upload static files to NAV CDN
        uses: navikt/frontend/actions/cdn-upload/v1@main
        with:
          cdn-team-name: aap
          source: ./.next/static
          destination: /aap-innsyn/_next

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          'registry': ghcr.io
          'username': ${{ github.actor }}
          'password': ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  'deployAppToProd':
    name: Deploy app to prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to PROD
        uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          'APIKEY': ${{ secrets.NAIS_DEPLOY_APIKEY }}
          'CLUSTER': prod-gcp
          'RESOURCE': .nais/nais.yaml,.nais/prod-alerts.yaml
          'VARS': .nais/prod.yaml